filebeat.inputs:
  - type: filestream
    id: backend-logs
    enabled: true
    parsers:
      - container: {}
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata: {}
  - drop_event:
      when:
        not:
          equals:
            container.labels.com_docker_compose_service: "backend"
  # Decode JSON string in message to top-level fields
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: ""
      overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
